package org.joda.time

object DateTimeConstants {
  val JANUARY = 1
  val FEBRUARY = 2
  val MARCH = 3
  val APRIL = 4
  val MAY = 5
  val JUNE = 6
  val JULY = 7
  val AUGUST = 8
  val SEPTEMBER = 9
  val OCTOBER = 10
  val NOVEMBER = 11
  val DECEMBER = 12
  val MONDAY = 1
  val TUESDAY = 2
  val WEDNESDAY = 3
  val THURSDAY = 4
  val FRIDAY = 5
  val SATURDAY = 6
  val SUNDAY = 7
  val AM = 0
  val PM = 1
  val BC = 0
  val BCE = 0
  val AD = 1
  val CE = 1
  val MILLIS_PER_SECOND = 1000
  val SECONDS_PER_MINUTE = 60
  val MILLIS_PER_MINUTE = MILLIS_PER_SECOND * SECONDS_PER_MINUTE
  val MINUTES_PER_HOUR = 60
  val SECONDS_PER_HOUR = SECONDS_PER_MINUTE * MINUTES_PER_HOUR
  val MILLIS_PER_HOUR = MILLIS_PER_MINUTE * MINUTES_PER_HOUR
  val HOURS_PER_DAY = 24
  val MINUTES_PER_DAY = MINUTES_PER_HOUR * HOURS_PER_DAY
  val SECONDS_PER_DAY = SECONDS_PER_HOUR * HOURS_PER_DAY
  val MILLIS_PER_DAY = MILLIS_PER_HOUR * HOURS_PER_DAY
  val DAYS_PER_WEEK = 7
  val HOURS_PER_WEEK = HOURS_PER_DAY * DAYS_PER_WEEK
  val MINUTES_PER_WEEK = MINUTES_PER_DAY * DAYS_PER_WEEK
  val SECONDS_PER_WEEK = SECONDS_PER_DAY * DAYS_PER_WEEK
  val MILLIS_PER_WEEK = MILLIS_PER_DAY * DAYS_PER_WEEK
}
